In [1]:
import pandas as pd

# nr

In [2]:
from processing import National, Base

In [3]:
nr = National()

## 2002

In [4]:
df_02 = pd.read_excel('data/nrsr/nrsr2002.xls')

In [5]:
df_02.head()

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 17,Unnamed: 18,Unnamed: 19,Unnamed: 20,Unnamed: 21,Unnamed: 22,Unnamed: 23,Unnamed: 24,Unnamed: 25,Unnamed: 26
0,NaN,Počet,Platné hlasy (počet/podiel),NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,\nOkres,platných\nhlasov\n spolu,SZS,SDKÚ,SDPO,SDĽ,SMER,HZDS,OKS,HZD,...,ANO,B-RRS,ŽAR,SDA,SNJ,NOSP,SNS,ROSA,ROISR,P SNS
2,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Bratislava I,30501,258,12400,23,296,2707,3539,356,852,...,1639,10,71,946,39,93,929,19,1,325
4,NaN,NaN,0.84,40.65,0.07,0.97,8.87,11.6,1.16,2.79,...,5.37,0.03,0.23,3.1,0.12,0.3,3.04,0.06,0,1.06

In [6]:
df_02 = nr.preprocess_2002(df_02)

In [7]:
df_02.head()

,Okres,SZS,SDKÚ,SDPO,SDĽ,SMER,HZDS,OKS,HZD,ROMA,...,B-RRS,ŽAR,SDA,SNJ,NOSP,SNS,ROSA,ROISR,P SNS,Kód Okresu
0,Bratislava I,258,12400,23,296,2707,3539,356,852,6,...,10,71,946,39,93,929,19,1,325,101
1,Bratislava II,586,22222,82,639,7737,8992,415,1997,19,...,29,252,1832,61,207,2404,67,24,1053,102
2,Bratislava III,388,13209,42,394,4889,5913,312,1256,7,...,12,141,1092,64,153,1569,60,5,800,103
3,Bratislava IV,505,20036,71,522,7196,6278,446,1611,13,...,18,270,1739,74,208,1775,75,11,872,104
4,Bratislava V,808,25795,84,746,9921,7467,554,1972,30,...,29,396,2378,79,220,2413,80,21,1541,105

In [8]:
df_02.shape

(80, 27)

In [9]:
nr.process_a(df_02, 2002)

In [10]:
df_test = nr.df

In [11]:
df_test.head()

,election_year,election_type,district_id,district_name,original_party_name,party_name,votes
0,2002,NR SR,101,Bratislava I,SZS,SZS,258
1,2002,NR SR,102,Bratislava II,SZS,SZS,586
2,2002,NR SR,103,Bratislava III,SZS,SZS,388
3,2002,NR SR,104,Bratislava IV,SZS,SZS,505
4,2002,NR SR,105,Bratislava V,SZS,SZS,808

## 2006

In [12]:
df_06 = pd.read_excel('data/nrsr/nrsr2006.xls')

In [13]:
df_06.head()

,"Počet a podiel platných hlasov odovzdaných pre politické strany podľa okresov, krajov a SR",Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 13,Unnamed: 14,Unnamed: 15,Unnamed: 16,Unnamed: 17,Unnamed: 18,Unnamed: 19,Unnamed: 20,Unnamed: 21,Unnamed: 22
0,NaN,Počet\nplatných\nhlasov\nspolu,Platné hlasy (počet / podiel),NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,"\nOkres, kraj,\nSR spolu",NaN,ĽB,S.O.S.,Misia 21,SDĽ,ZRS,KDH,SLNKO,ANO,...,OKS,PS,ĽS - HZDS,ASV,KSS,SĽS,SDKÚ - DS,SMER,SNS,NÁDEJ
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Bratislava I,23 927,20,6,33,28,9,2 621,34,224,...,295,52,1 511,13,545,48,10 676,3 522,1 417,71
4,NaN,NaN,"0,08","0,02","0,13","0,11","0,03","10,95","0,14","0,93",...,"1,23","0,21","6,31","0,05","2,27","0,20","44,61","14,71","5,92","0,29"

In [14]:
df_06 = National.preprocess_2006(df_06)

In [15]:
df_06.head()

,Okres,ĽB,S.O.S.,Misia 21,SDĽ,ZRS,KDH,SLNKO,ANO,HZD,...,PS,ĽS - HZDS,ASV,KSS,SĽS,SDKÚ - DS,SMER,SNS,NÁDEJ,Kód Okresu
0,Bratislava I,20,6,33,28,9,2 621,34,224,122,...,52,1 511,13,545,48,10 676,3 522,1 417,71,101
1,Bratislava II,62,27,50,92,55,3 945,109,659,209,...,123,3 784,60,1 540,99,19 958,10 860,4 168,228,102
2,Bratislava III,37,14,39,49,23,2 565,48,408,125,...,61,2 474,24,1 094,63,11 900,6 785,2 817,162,103
3,Bratislava IV,73,15,70,52,48,3 826,82,812,155,...,116,2 705,55,1 259,110,18 218,9 397,3 583,225,104
4,Bratislava V,75,17,42,100,63,4 138,108,932,240,...,208,3 006,52,1 586,153,22 012,12 925,4 907,253,105

In [16]:
df_06.shape

(80, 23)

In [17]:
df_06.shape

(80, 23)

In [18]:
nr.process_a(df_06, 2006)

In [19]:
nr.df.shape

(3680, 7)

## 2010

In [20]:
df_10 = pd.read_excel('data/nrsr/nrsr2010.xls')

In [21]:
df_10.head()

,Kód\nokresu,Názov\nokresu,Počet\nvoleb.\nokrskov,Počet\nvoličov\nzapísaných\nv zoznamoch\nvoličov,"Počet\nvoličov,\nktorí sa\nzúčastnili\nna hlasovaní","Počet\nvoličov,\nktorí\nzaslali\nnávratnú\nobálku\nz cudziny","Počet\nvoličov,\nktorí\nhlasovali\nosobne",Počet\nplatných\nhlasov\nspolu,EDS,Únia,...,KSS,SNS,ND,ZRS,KDH,ĽSNS,SDKÚ - DS,AZEN,SMER,MOST - HÍD
0,101,Bratislava I,34,38113,25372,168,25188,25045,42,173,...,80,700,65,9,2739,95,8161,24,4738,2772
1,102,Bratislava II,107,97490,62356,213,62094,61750,104,682,...,237,2208,163,24,4666,345,17742,54,15136,5954
2,103,Bratislava III,64,54886,36477,137,36323,36097,61,303,...,173,1454,109,29,3090,209,10349,45,9310,2508
3,104,Bratislava IV,82,84085,54136,270,53806,53615,92,617,...,185,1765,144,41,4699,313,15738,79,12888,3924
4,105,Bratislava V,107,105818,64554,287,64229,64110,111,700,...,262,2325,186,43,4530,474,18882,82,15232,5133

In [22]:
df_10 = National.preprocess_2010(df_10)

In [23]:
df_10.head()

,Kód Okresu,Okres,EDS,Únia,SRK,Paliho Kapurková,SaS,SDĽ,SMK - MKP,ĽS - HZDS,KSS,SNS,ND,ZRS,KDH,ĽSNS,SDKÚ - DS,AZEN,SMER,MOST - HÍD
0,101,Bratislava I,42,173,14,118,4159,323,202.0,631,80,700,65,9,2739,95,8161,24,4738,2772
1,102,Bratislava II,104,682,18,373,10592,1077,622.0,1753,237,2208,163,24,4666,345,17742,54,15136,5954
2,103,Bratislava III,61,303,10,279,6189,719,174.0,1086,173,1454,109,29,3090,209,10349,45,9310,2508
3,104,Bratislava IV,92,617,4,363,10257,1014,183.0,1309,185,1765,144,41,4699,313,15738,79,12888,3924
4,105,Bratislava V,111,700,24,552,12219,1433,425.0,1497,262,2325,186,43,4530,474,18882,82,15232,5133

In [24]:
nr.process_a(df_10, 2010)

In [25]:
nr.df.shape

(5102, 7)

## 2012

In [26]:
df_12 = pd.read_excel('data/nrsr/nrsr2012.xls')

In [27]:
df_12.head()

,Kód\nokresu,Názov\nokresu,Počet\nvoleb.\nokrskov,Počet\nvoličov\nzapísaných\nv zoznamoch\nvoličov,"Počet\nvoličov,\nktorí sa\nzúčastnili\nna hlasovaní","Počet\nvoličov,\nktorí\nzaslali\nnávratnú\nobálku\nz cudziny","Počet\nvoličov,\nktorí\nhlasovali\nosobne",Počet\nplatných\nhlasov\nspolu,Zelení,KDH,...,99%,ĽS-HZDS,+1 HLAS,SF,Obyčajní ľudia,SDKÚ - DS,SOSKA,SMK-MKP,SSS - NM,SŽS
0,101,Bratislava I,34,38218,24851,184,24628,24479,53,3013,...,267,111,6,71,28,4495,32,179,157,28
1,102,Bratislava II,107,100712,62586,243,62181,61560,167,5583,...,794,305,47,337,89,8557,121,601,504,75
2,103,Bratislava III,66,56713,36331,191,36122,35752,97,3512,...,433,189,16,136,52,5029,60,165,246,26
3,104,Bratislava IV,82,85025,54439,260,54017,53410,148,5203,...,674,218,32,264,73,7378,110,187,392,55
4,105,Bratislava V,107,105930,64075,920,63104,63090,203,5342,...,962,237,60,400,117,8061,133,425,676,65

In [28]:
df_12 = National.preprocess_2010(df_12)

In [29]:
df_12.head()

,Kód Okresu,Okres,Zelení,KDH,SDĽ,SNS,OĽaNO,SaS,PaS,NÁŠ KRAJ,...,99%,ĽS-HZDS,+1 HLAS,SF,Obyčajní ľudia,SDKÚ - DS,SOSKA,SMK-MKP,SSS - NM,SŽS
0,101,Bratislava I,53,3013,36,653,2198,3951,75,18,...,267,111,6,71,28,4495,32,179,157,28
1,102,Bratislava II,167,5583,69,2059,5182,8689,237,43,...,794,305,47,337,89,8557,121,601,504,75
2,103,Bratislava III,97,3512,39,1422,3409,4951,158,22,...,433,189,16,136,52,5029,60,165,246,26
3,104,Bratislava IV,148,5203,64,1866,5151,8097,226,27,...,674,218,32,264,73,7378,110,187,392,55
4,105,Bratislava V,203,5342,73,2244,6090,9010,368,46,...,962,237,60,400,117,8061,133,425,676,65

In [30]:
df_12.shape

(79, 28)

In [31]:
nr.process_a(df_12, 2012)

## 2016

In [32]:
df_16 = pd.read_excel('data/nrsr/nrsr2016.xlsx')

In [33]:
df_16.head()

,Výsledky hlasovania pre politické subjekty podľa okresov,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 85,Unnamed: 86,Unnamed: 87,Unnamed: 88,Unnamed: 89,Unnamed: 90,Unnamed: 91,Unnamed: 92,Unnamed: 93,Unnamed: 94
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Kód okresu,Okres,Počet platných hlasov spolu,TIP,NaN,NaN,NaN,STRANA MODERNÉHO SLOVENSKA (SMS),NaN,NaN,...,NaN,NaN,PD,NaN,NaN,NaN,SaS,NaN,NaN,NaN
2,NaN,NaN,NaN,Počet platných hlasov,Podiel platných hlasov v %,"Počet voličov, ktorí využili právo prednostnéh...","Podiel voličov, ktorí využili právo prednostné...",Počet platných hlasov,Podiel platných hlasov v %,"Počet voličov, ktorí využili právo prednostnéh...",...,"Počet voličov, ktorí využili právo prednostnéh...","Podiel voličov, ktorí využili právo prednostné...",Počet platných hlasov,Podiel platných hlasov v %,"Počet voličov, ktorí využili právo prednostnéh...","Podiel voličov, ktorí využili právo prednostné...",Počet platných hlasov,Podiel platných hlasov v %,"Počet voličov, ktorí využili právo prednostnéh...","Podiel voličov, ktorí využili právo prednostné..."
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,101,Bratislava I,26227,45,0.17,35,77.77,16,0.06,12,...,125,76.68,38,0.14,31,81.57,7764,29.6,6549,84.35

In [34]:
df_16 = National.preprocess_2016(df_16)

In [35]:
df_16.head()

1,Kód Okresu,Okres,TIP,STRANA MODERNÉHO SLOVENSKA (SMS),OBYČAJNÍ ĽUDIA a nezávislé osobnosti (OĽANO - NOVA),DS - Ľudo Kaník,ŠANCA,SME RODINA - Boris Kollár,SZS,KOALÍCIA SPOLOČNE ZA SLOVENSKO,...,KSS,SDKÚ-DS,SMER-SD,KDH,SKOK!,ĽS Naše Slovensko,#SIEŤ,SMK-MKP,PD,SaS
4,101,Bratislava I,45,16,4050,15,60,1006,152,11,...,54,133,3929,1385,357,707,1895,163,38,7764
5,102,Bratislava II,197,38,8890,33,126,4770,413,56,...,217,270,12421,2712,905,2685,4366,686,106,17800
6,103,Bratislava III,96,17,5565,23,78,2286,306,24,...,142,156,7608,1614,523,1448,2709,159,50,10485
7,104,Bratislava IV,137,29,8721,23,108,3890,447,34,...,216,350,10672,2340,807,2605,3985,184,83,15474
8,105,Bratislava V,171,47,9388,23,136,5432,536,64,...,234,231,12307,2355,936,3211,4458,344,225,17244

In [36]:
df_16.shape

(80, 25)

In [37]:
nr.process_a(df_16, 2016)

In [38]:
nr.df.shape

(8996, 7)

## 2020

In [39]:
df_20 = pd.read_excel('data/nrsr/nrsr2020.xlsx')

In [40]:
df_20.head()

,Počet a podiel platných hlasov odovzdaných pre politické subjekty za okresy,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Kód kraja,Názov kraja,Kód územného obvodu,Názov územného obvodu,Kód okresu,Názov okresu,Číslo politického subjektu,Názov politického subjektu,Počet platných hlasov,Podiel platných hlasov v %,"Počet voličov, ktorí využili právo prednostnéh...","Podiel voličov, ktorí využili právo prednostné..."
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1,Bratislavský kraj,101,Bratislava,101,Bratislava I,1,Slovenská ľudová strana Andreja Hlinku,18,0.05,14,77.77
4,1,Bratislavský kraj,101,Bratislava,101,Bratislava I,2,DOBRÁ VOĽBA,638,2.1,523,81.97

In [41]:
df_20 = National.preprocess_2020(df_20)

In [42]:
df_20.head()

1 Kód Okresu         Okres                              party_name votes
3        101  Bratislava I  Slovenská ľudová strana Andreja Hlinku    18
4        101  Bratislava I                             DOBRÁ VOĽBA   638
5        101  Bratislava I                    Sloboda a Solidarita  4566
6        101  Bratislava I                              SME RODINA  1042
7        101  Bratislava I                 Slovenské Hnutie Obrody     9

In [43]:
nr.process_b(df_20, 2020)

In [44]:
nr.df.shape

(10911, 7)

## 2023

In [45]:
df_23 = pd.read_excel('data/nrsr/nrsr2023.xlsx')

In [46]:
df_23.head()

,Počet a podiel platných hlasov odovzdaných pre politické subjekty za okresy,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Kód kraja,Názov kraja,Kód územného obvodu,Názov územného obvodu,Kód okresu,Názov okresu,Číslo politického subjektu,Názov politického subjektu,Počet platných hlasov,Podiel platných hlasov v %,"Počet voličov, ktorí využili právo prednostnéh...","Podiel voličov, ktorí využili právo prednostné..."
2,1,Bratislavský kraj,101,Bratislava,101,Bratislava I,1,Pirátska strana - Slovensko,49,0.17,30,61.22
3,1,Bratislavský kraj,101,Bratislava,101,Bratislava I,2,PRINCÍP,11,0.03,8,72.72
4,1,Bratislavský kraj,101,Bratislava,101,Bratislava I,3,Progresívne Slovensko,11804,41.59,9545,80.86

In [47]:
df_23 = National.preprocess_2020(df_23)

In [48]:
df_23.head()

1,Kód Okresu,Okres,party_name,votes
2,101,Bratislava I,Pirátska strana - Slovensko,49
3,101,Bratislava I,PRINCÍP,11
4,101,Bratislava I,Progresívne Slovensko,11804
5,101,Bratislava I,SPOLOČNE OBČANIA SLOVENSKA,6
6,101,Bratislava I,"OĽANO A PRIATELIA: OBYČAJNÍ ĽUDIA (OĽANO), NEZ...",1172

In [50]:
nr.process_b(df_23, 2023)

In [52]:
nr.df.shape

(12909, 7)